ALTER TABLE "Province"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "City"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "District"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
