export type AdminDashboardStats = {
  packages: number;
  provinces: number;
  cities: number;
  districts: number;
  divarCategories: number;
  divarCategoryFilters: number;
  postsToAnalyzePending: number;
  notifications: number;
  adminDivarSessions: number;
  adminArkaSessions: number;
  news: number;
  newsCategories: number;
  newsTags: number;
  newsSources: number;
  blog: number;
  blogCategories: number;
  blogTags: number;
  blogSources: number;
  slides: number;
  seoSettings: number;
  websiteSettings: number;
};
