ALTER TABLE "PaymentRequest" ADD COLUMN "durationDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PaymentRequest" ADD COLUMN "freeDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PaymentRequest" ADD COLUMN "features" JSONB NOT NULL DEFAULT '{}';
