-- AlterTable
ALTER TABLE "PaymentRequest" ADD COLUMN IF NOT EXISTS "originalPrice" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "PaymentRequest" ADD COLUMN IF NOT EXISTS "discountAmount" DECIMAL(12,2);
ALTER TABLE "PaymentRequest" ADD COLUMN IF NOT EXISTS "taxPercentage" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PaymentRequest" ADD COLUMN IF NOT EXISTS "taxAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "PaymentRequest" ADD COLUMN IF NOT EXISTS "finalAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "PaymentRequest" ADD COLUMN IF NOT EXISTS "inviteBonusDays" INTEGER;

-- AlterTable
ALTER TABLE "WebsiteSetting" ADD COLUMN IF NOT EXISTS "taxPercentage" DOUBLE PRECISION NOT NULL DEFAULT 0;
